# miniboot-switch: mounts main root, switch_roots into /opt/miniboot-root
MODULES=(ext4 sd_mod ahci virtio virtio_ring virtio_blk virtio_pci virtio_scsi nvme vfat nls_iso8859_1)
BINARIES=()
FILES=()
HOOKS=(base miniswitch)
COMPRESSION="zstd"
