#!/bin/bash
build() {
    add_file /usr/lib/miniboot/detect-root.sh /detect-root.sh 0755
    add_binary kexec
    add_file /usr/lib/miniboot/miniboot.sh /miniboot.sh 0755
}
help() {
    cat <<HELPEOF
Miniboot kexec boot menu. Boot with rdinit=/miniboot.sh
HELPEOF
}
